attributes:
  aislante: AISLANTE
  aislante termico: AISLANTE
  antideslizante: ANTIDESLIZANTE
  bordado: BORDADO
  bordados: BORDADO
  clasica: CLASICO
  clasico: CLASICO
  compacta: COMPACTO
  compacto: COMPACTO
  ecologico: ECOLOGICO
  ejecutivo: EJECUTIVO
  elegante: ELEGANTE
  ergonomica: ERGONOMICO
  ergonomico: ERGONOMICO
  estampado: ESTAMPADO
  estampados: ESTAMPADO
  grabado: GRABADO
  grabados: GRABADO
  impermeable: IMPERMEABLE
  inalambrica: INALAMBRICO
  inalambrico: INALAMBRICO
  innovador: INNOVADOR
  innovadora: INNOVADOR
  ligera: LIGERO
  ligero: LIGERO
  liviana: LIGERO
  liviano: LIGERO
  moderna: MODERNO
  moderno: MODERNO
  multifuncional: MULTIFUNCIONAL
  multiusos: MULTIFUNCIONAL
  personaliza: PERSONALIZABLE
  personalizable: PERSONALIZABLE
  personalizada: PERSONALIZABLE
  personalizadas: PERSONALIZABLE
  personalizado: PERSONALIZABLE
  personalizados: PERSONALIZABLE
  plegable: PLEGABLE
  portatil: PORTATIL
  portatiles: PORTATIL
  practica: PRACTICO
  practico: PRACTICO
  premium: PREMIUM
  recargable: RECARGABLE
  recargables: RECARGABLE
  resistente: RESISTENTE
  resistentes: RESISTENTE
  reutilizable: REUTILIZABLE
  serigrafia: ESTAMPADO
  sostenible: ECOLOGICO
  termica: TERMICO
  termico: TERMICO
  wireless: INALAMBRICO
