colors:
  amarilla: AMARILLO
  amarillo: AMARILLO
  anaranjado: NARANJA
  azul: AZUL
  azul claro: AZUL
  azul marino: AZUL
  azul oscuro: AZUL
  azules: AZUL
  beige: BEIGE
  beige claro: BEIGE
  blanca: BLANCO
  blancas: BLANCO
  blanco: BLANCO
  blancos: BLANCO
  cafe: CAFE
  cafe claro: CAFE
  cafe oscuro: CAFE
  combinado: MULTICOLOR
  crema: BEIGE
  dorada: DORADO
  dorado: DORADO
  estandar: ESTANDAR
  gris: GRIS
  gris claro: GRIS
  gris oscuro: GRIS
  gris plata: GRIS
  grises: GRIS
  marron: CAFE
  marrón: CAFE
  morada: MORADO
  morado: MORADO
  multicolor: MULTICOLOR
  naranja: NARANJA
  negra: NEGRO
  negras: NEGRO
  negro: NEGRO
  negros: NEGRO
  oro: DORADO
  plateada: PLATEADO
  plateado: PLATEADO
  purpura: MORADO
  púrpura: MORADO
  roja: ROJO
  rojas: ROJO
  rojo: ROJO
  rojo oscuro: ROJO
  rojo vivo: ROJO
  rojos: ROJO
  rosa: ROSA
  rosada: ROSA
  rosado: ROSA
  rosado claro: ROSA
  rosado pastel: ROSA
  surtido: MULTICOLOR
  transparente: TRANSPARENTE
  verde: VERDE
  verde claro: VERDE
  verde militar: VERDE
  verde oscuro: VERDE
  verdes: VERDE
  violeta: MORADO
