materials:
  acero: METAL
  acrilico: SINTETICO
  acrílico: SINTETICO
  aglomerado: MADERA
  algodon: ALGODON
  algodón: ALGODON
  aluminio: METAL
  bamboo: BAMBU
  bambu: BAMBU
  barro: CERAMICA
  bronce: METAL
  cannamo: YUTE
  caucho: CAUCHO
  ceramica: CERAMICA
  cobre: METAL
  contrachapado: MADERA
  corcho: CORCHO
  cristal: VIDRIO
  cristal templado: VIDRIO
  cromo: METAL
  cuero: CUERO
  cáñamo: YUTE
  esmalte: CERAMICA
  estanyo: METAL
  estaño: METAL
  fibra: SINTETICO
  fibras: SINTETICO
  fierro: METAL
  goma: CAUCHO
  greda: CERAMICA
  hierro: METAL
  inoxidable: METAL
  laton: METAL
  latón: METAL
  lienzo: LIENZO
  lino: TELA
  lona: LONA
  loza: CERAMICA
  lycra: SINTETICO
  madera: MADERA
  mdf: MADERA
  metal: METAL
  metalica: METAL
  metalicas: METAL
  metalico: METAL
  metalicos: METAL
  neopreno: NEOPRENO
  niquel: METAL
  nylon: SINTETICO
  níquel: METAL
  piel: CUERO
  plastica: PLASTICO
  plasticas: PLASTICO
  plastico: PLASTICO
  plasticos: PLASTICO
  plomo: METAL
  poliester: POLIESTER
  polietileno: PLASTICO
  polimero: PLASTICO
  polipropileno: POLIPROPILENO
  poliéster: POLIESTER
  porcelana: CERAMICA
  rpet: RPET
  seda: TELA
  silicona: SILICONA
  silicone: SILICONA
  sintetica: SINTETICO
  sintetico: SINTETICO
  spandex: SINTETICO
  tela: TELA
  tergal: SINTETICO
  textil: TELA
  titanio: METAL
  vidrio: VIDRIO
  vidrio templado: VIDRIO
  yuta: YUTE
  yute: YUTE
  zamak: METAL
