from dataclasses import dataclass, field


@dataclass
class _CommercialProfile:
    industries: list[str] = field(default_factory=list)
    customer_profiles: list[str] = field(default_factory=list)
    executive_level: str = "low"
    premium_level: str = "basic"
    commercial_value: str = "economic"
    gift_occasions: list[str] = field(default_factory=list)
    campaigns: list[str] = field(default_factory=list)
    use_cases: list[str] = field(default_factory=list)
    corporate_affinity: float = 0.0
    perceived_value: str = "estandar"
    commercial_tags: list[str] = field(default_factory=list)
    boost_tags: list[str] = field(default_factory=list)
    penalty_tags: list[str] = field(default_factory=list)


FAMILY_PROFILES: dict[str, _CommercialProfile] = {
    "USB": _CommercialProfile(
        industries=["TECNOLOGIA", "TELECOMUNICACIONES", "EDUCACION", "STARTUPS", "CONSULTORIA"],
        customer_profiles=["EJECUTIVO", "COMERCIAL", "ADMINISTRATIVO", "PROFESIONAL"],
        executive_level="medium",
        premium_level="standard",
        commercial_value="standard",
        gift_occasions=["EVENTOS", "FERIAS", "LANZAMIENTOS", "CAPACITACION", "CONFERENCIAS", "CONGRESOS"],
        campaigns=["LANZAMIENTO", "FERIA", "CONGRESO", "EVENTO_TECNOLOGIA"],
        use_cases=["ALMACENAMIENTO", "TRANSFERENCIA_DATOS", "PROMOCIONAL_TECNOLOGIA"],
        corporate_affinity=0.7,
        perceived_value="corporativo",
        commercial_tags=["corporativo", "tecnologico", "util", "promocional"],
        boost_tags=["tecnologia", "corporativo", "evento", "feria", "congreso", "lanzamiento"],
    ),
    "BOTELLA": _CommercialProfile(
        industries=["ARQUITECTURA", "INGENIERIA", "CONSTRUCCION", "EDUCACION", "SALUD", "DEPORTES", "OUTDOOR"],
        customer_profiles=["EJECUTIVO", "VIP", "ADMINISTRATIVO", "DEPORTISTA", "VIAJERO"],
        executive_level="medium",
        premium_level="standard",
        commercial_value="standard",
        gift_occasions=["BIENVENIDA", "CONVENCION", "EVENTO_CORPORATIVO", "CAPACITACION", "EVENTO_DEPORTIVO"],
        campaigns=["BIENVENIDA", "EVENTO_CORPORATIVO", "CAPACITACION", "FERIA"],
        use_cases=["HIDRATACION", "EVENTOS", "OFICINA", "VIAJES", "DEPORTES"],
        corporate_affinity=0.7,
        perceived_value="corporativo",
        commercial_tags=["corporativo", "util", "practico", "estilo"],
        boost_tags=["arquitectura", "ingenieria", "construccion", "evento", "bienvenida", "ejecutivo"],
    ),
    "TERMO": _CommercialProfile(
        industries=["ARQUITECTURA", "INGENIERIA", "CONSTRUCCION", "EDUCACION", "SALUD", "OUTDOOR"],
        customer_profiles=["EJECUTIVO", "VIP", "PROFESIONAL"],
        executive_level="high",
        premium_level="premium",
        commercial_value="valuable",
        gift_occasions=["BIENVENIDA", "CONVENCION", "EVENTO_CORPORATIVO", "PREMIOS", "RECONOCIMIENTO"],
        campaigns=["BIENVENIDA", "EVENTO_CORPORATIVO", "PREMIOS", "RECONOCIMIENTO"],
        use_cases=["HIDRATACION", "OFICINA", "VIAJES", "EVENTOS_FORMALES"],
        corporate_affinity=0.85,
        perceived_value="alta_calidad",
        commercial_tags=["premium", "ejecutivo", "alta_calidad", "corporativo", "exclusivo"],
        boost_tags=["premium", "ejecutivo", "arquitectura", "ingenieria", "vip", "bienvenida"],
    ),
    "MUG": _CommercialProfile(
        industries=["EDUCACION", "TECNOLOGIA", "CONSULTORIA", "FINANCIERO", "CORPORATIVO"],
        customer_profiles=["EJECUTIVO", "ADMINISTRATIVO", "PROFESIONAL"],
        executive_level="low",
        premium_level="standard",
        commercial_value="economic",
        gift_occasions=["BIENVENIDA", "EVENTOS", "CAPACITACION", "OFICINA"],
        campaigns=["BIENVENIDA", "EVENTO", "CAPACITACION", "OFICINA"],
        use_cases=["OFICINA", "DESAYUNO", "PAUSA_CAFE", "EVENTOS", "BIENVENIDA"],
        corporate_affinity=0.5,
        perceived_value="corporativo",
        commercial_tags=["corporativo", "oficina", "cotidiano", "util"],
        boost_tags=["oficina", "bienvenida", "corporativo", "educacion"],
    ),
    "VASO": _CommercialProfile(
        industries=["EDUCACION", "TECNOLOGIA", "CONSULTORIA", "EVENTOS", "CORPORATIVO"],
        customer_profiles=["ADMINISTRATIVO", "PROFESIONAL", "GENERAL"],
        executive_level="low",
        premium_level="standard",
        commercial_value="economic",
        gift_occasions=["EVENTOS", "FERIAS", "CAPACITACION", "OFICINA"],
        campaigns=["EVENTO", "FERIA", "CAPACITACION"],
        use_cases=["OFICINA", "EVENTOS", "PAUSA"],
        corporate_affinity=0.4,
        perceived_value="estandar",
        commercial_tags=["basico", "util", "promocional"],
        boost_tags=["evento", "feria", "promocional"],
    ),
    "LAPICERO": _CommercialProfile(
        industries=["EDUCACION", "CONSULTORIA", "TECNOLOGIA", "FINANCIERO", "CORPORATIVO", "LEGAL"],
        customer_profiles=["EJECUTIVO", "ADMINISTRATIVO", "PROFESIONAL"],
        executive_level="medium",
        premium_level="standard",
        commercial_value="economic",
        gift_occasions=["CAPACITACION", "WORKSHOP", "CONFERENCIAS", "EVENTOS", "OFICINA"],
        campaigns=["CAPACITACION", "WORKSHOP", "EVENTO", "OFICINA"],
        use_cases=["ESCRITURA", "OFICINA", "REUNIONES", "CAPACITACION", "TOMA_NOTAS"],
        corporate_affinity=0.6,
        perceived_value="corporativo",
        commercial_tags=["corporativo", "oficina", "util", "papeleria"],
        boost_tags=["oficina", "capacitacion", "educacion", "corporativo", "ejecutivo"],
    ),
    "BOLSO": _CommercialProfile(
        industries=["TECNOLOGIA", "CONSULTORIA", "EDUCACION", "VIAJES", "CORPORATIVO"],
        customer_profiles=["EJECUTIVO", "COMERCIAL", "VIAJERO", "PROFESIONAL"],
        executive_level="high",
        premium_level="standard",
        commercial_value="valuable",
        gift_occasions=["VIAJES", "EVENTOS", "CAPACITACION", "CONFERENCIAS", "BIENVENIDA"],
        campaigns=["VIAJES", "EVENTO", "CAPACITACION", "BIENVENIDA"],
        use_cases=["TRANSPORTE", "VIAJES", "OFICINA", "REUNIONES_EXTERNAS"],
        corporate_affinity=0.75,
        perceived_value="ejecutivo",
        commercial_tags=["ejecutivo", "corporativo", "practico", "profesional"],
        boost_tags=["ejecutivo", "viaje", "corporativo", "profesional", "tecnologia"],
    ),
    "AGENDA": _CommercialProfile(
        industries=["EDUCACION", "CONSULTORIA", "TECNOLOGIA", "FINANCIERO", "CORPORATIVO", "LEGAL"],
        customer_profiles=["EJECUTIVO", "ADMINISTRATIVO", "PROFESIONAL"],
        executive_level="high",
        premium_level="standard",
        commercial_value="standard",
        gift_occasions=["PLANIFICACION", "WORKSHOP", "CONFERENCIAS", "CAPACITACION", "BIENVENIDA"],
        campaigns=["PLANIFICACION", "CAPACITACION", "WORKSHOP", "BIENVENIDA"],
        use_cases=["TOMA_NOTAS", "PLANIFICACION", "REUNIONES", "CAPACITACION"],
        corporate_affinity=0.7,
        perceived_value="ejecutivo",
        commercial_tags=["ejecutivo", "corporativo", "papeleria", "profesional"],
        boost_tags=["ejecutivo", "corporativo", "oficina", "profesional", "capacitacion"],
    ),
    "GORRA": _CommercialProfile(
        industries=["DEPORTES", "OUTDOOR", "EVENTOS", "CONSTRUCCION", "EDUCACION"],
        customer_profiles=["DEPORTISTA", "GENERAL", "JOVEN"],
        executive_level="low",
        premium_level="basic",
        commercial_value="economic",
        gift_occasions=["EVENTOS", "FERIAS", "ACTIVIDADES_AIRE_LIBRE", "EVENTO_DEPORTIVO"],
        campaigns=["EVENTO", "FERIA", "PROMOCION", "LANZAMIENTO"],
        use_cases=["PROTECCION_SOLAR", "EVENTOS", "PROMOCIONES", "UNIFORME"],
        corporate_affinity=0.3,
        perceived_value="casual",
        commercial_tags=["casual", "promocional", "deportivo"],
        boost_tags=["deportes", "evento", "promocional", "feria"],
    ),
    "LLAVERO": _CommercialProfile(
        industries=["CORPORATIVO", "EVENTOS", "TECNOLOGIA", "SALUD", "EDUCACION", "GENERAL"],
        customer_profiles=["GENERAL", "ADMINISTRATIVO", "COMERCIAL"],
        executive_level="low",
        premium_level="basic",
        commercial_value="economic",
        gift_occasions=["FERIAS", "EVENTOS", "PROMOCIONES", "LANZAMIENTOS", "CAPACITACION"],
        campaigns=["FERIA", "PROMOCION", "LANZAMIENTO", "EVENTO"],
        use_cases=["PROMOCION", "EVENTOS", "REGALO_CORPORATIVO", "FIDELIZACION"],
        corporate_affinity=0.3,
        perceived_value="promocional",
        commercial_tags=["promocional", "economico", "accesorio"],
        boost_tags=["feria", "evento", "promocional", "lanzamiento"],
    ),
    "PARAGUAS": _CommercialProfile(
        industries=["CORPORATIVO", "FINANCIERO", "CONSULTORIA", "SEGUROS", "GOBIERNO"],
        customer_profiles=["EJECUTIVO", "ADMINISTRATIVO", "COMERCIAL"],
        executive_level="medium",
        premium_level="standard",
        commercial_value="standard",
        gift_occasions=["EVENTOS_CORPORATIVOS", "BIENVENIDA", "CLIENTES", "FERIAS", "LLUVIA"],
        campaigns=["BIENVENIDA", "EVENTO_CORPORATIVO", "CLIENTES", "FERIA"],
        use_cases=["LLUVIA", "EVENTOS_EXTERIORES", "MOVILIDAD"],
        corporate_affinity=0.6,
        perceived_value="corporativo",
        commercial_tags=["corporativo", "util", "practico"],
        boost_tags=["corporativo", "ejecutivo", "bienvenida", "cliente"],
    ),
    "TOALLA": _CommercialProfile(
        industries=["DEPORTES", "SALUD", "BIENESTAR", "OUTDOOR", "HOTELERIA"],
        customer_profiles=["DEPORTISTA", "GENERAL"],
        executive_level="low",
        premium_level="standard",
        commercial_value="economic",
        gift_occasions=["EVENTOS_DEPORTIVOS", "GIMNASIO", "BIENVENIDA", "PROMOCIONES"],
        campaigns=["EVENTO_DEPORTIVO", "PROMOCION", "GIMNASIO"],
        use_cases=["DEPORTES", "GIMNASIO", "PLAYA", "SPA"],
        corporate_affinity=0.3,
        perceived_value="practico",
        commercial_tags=["deportivo", "practico", "util"],
        boost_tags=["deportes", "salud", "bienestar", "gimnasio"],
    ),
    "AUDIFONOS": _CommercialProfile(
        industries=["TECNOLOGIA", "TELECOMUNICACIONES", "STARTUPS", "EDUCACION", "CORPORATIVO"],
        customer_profiles=["EJECUTIVO", "TECNOLOGICO", "PROFESIONAL", "VIAJERO"],
        executive_level="medium",
        premium_level="premium",
        commercial_value="valuable",
        gift_occasions=["EVENTOS", "LANZAMIENTOS", "CONFERENCIAS", "TELETRABAJO", "VIAJES"],
        campaigns=["LANZAMIENTO", "EVENTO_TECNOLOGIA", "CONFERENCIA", "BIENVENIDA"],
        use_cases=["TELETRABAJO", "COMUNICACION", "ENTRETENIMIENTO", "VIAJES", "OFICINA"],
        corporate_affinity=0.7,
        perceived_value="alta_calidad",
        commercial_tags=["tecnologico", "premium", "moderno", "ejecutivo"],
        boost_tags=["tecnologia", "ejecutivo", "premium", "moderno", "startup", "conferencia"],
    ),
    "CARGADOR": _CommercialProfile(
        industries=["TECNOLOGIA", "TELECOMUNICACIONES", "STARTUPS", "VIAJES", "CORPORATIVO"],
        customer_profiles=["EJECUTIVO", "COMERCIAL", "VIAJERO", "TECNOLOGICO"],
        executive_level="high",
        premium_level="premium",
        commercial_value="valuable",
        gift_occasions=["EVENTOS", "FERIAS", "LANZAMIENTOS", "VIAJES", "CONFERENCIAS"],
        campaigns=["LANZAMIENTO", "EVENTO_TECNOLOGIA", "FERIA", "VIAJES"],
        use_cases=["CARGA_DISPOSITIVOS", "VIAJES", "EVENTOS", "OFICINA", "MOVILIDAD"],
        corporate_affinity=0.8,
        perceived_value="alta_calidad",
        commercial_tags=["tecnologico", "premium", "util", "practico", "moderno"],
        boost_tags=["tecnologia", "ejecutivo", "viaje", "evento", "feria", "lanzamiento"],
    ),
    "MOUSE": _CommercialProfile(
        industries=["TECNOLOGIA", "STARTUPS", "EDUCACION", "CORPORATIVO", "TELECOMUNICACIONES"],
        customer_profiles=["EJECUTIVO", "TECNOLOGICO", "ADMINISTRATIVO", "PROFESIONAL"],
        executive_level="medium",
        premium_level="standard",
        commercial_value="standard",
        gift_occasions=["OFICINA", "TELETRABAJO", "CONFERENCIAS", "CAPACITACION", "BIENVENIDA"],
        campaigns=["OFICINA", "TELETRABAJO", "EVENTO_TECNOLOGIA"],
        use_cases=["TRABAJO_OFICINA", "COMPUTACION", "TELETRABAJO"],
        corporate_affinity=0.6,
        perceived_value="corporativo",
        commercial_tags=["tecnologico", "corporativo", "oficina", "util"],
        boost_tags=["tecnologia", "oficina", "corporativo", "teletrabajo"],
    ),
    "CALCULADORA": _CommercialProfile(
        industries=["EDUCACION", "FINANCIERO", "CONTABILIDAD", "SEGUROS", "CORPORATIVO"],
        customer_profiles=["ADMINISTRATIVO", "CONTABLE", "PROFESIONAL", "ESTUDIANTE"],
        executive_level="low",
        premium_level="standard",
        commercial_value="economic",
        gift_occasions=["OFICINA", "CAPACITACION", "EVENTOS", "UNIVERSIDAD"],
        campaigns=["OFICINA", "CAPACITACION", "UNIVERSIDAD"],
        use_cases=["CALCULO", "OFICINA", "CONTABILIDAD"],
        corporate_affinity=0.5,
        perceived_value="corporativo",
        commercial_tags=["corporativo", "oficina", "util", "papeleria"],
        boost_tags=["oficina", "educacion", "financiero", "corporativo"],
    ),
    "NEVERA": _CommercialProfile(
        industries=["CONSTRUCCION", "OUTDOOR", "EVENTOS", "SALUD", "DEPORTES", "LOGISTICA"],
        customer_profiles=["TRABAJADOR", "DEPORTISTA", "EVENTO", "LOGISTICA"],
        executive_level="low",
        premium_level="standard",
        commercial_value="standard",
        gift_occasions=["EVENTOS_AIRE_LIBRE", "FERIAS", "CAPACITACION", "OBRAS", "PICNIC"],
        campaigns=["EVENTO", "FERIA", "OBRA", "CAPACITACION"],
        use_cases=["REFRIGERACION", "EVENTOS_EXTERIORES", "TRANSPORTE_ALIMENTOS", "OBRAS"],
        corporate_affinity=0.4,
        perceived_value="practico",
        commercial_tags=["practico", "util", "eventos", "obra"],
        boost_tags=["construccion", "evento", "obra", "feria", "outdoor"],
    ),
    "RELOJ": _CommercialProfile(
        industries=["CORPORATIVO", "FINANCIERO", "CONSULTORIA", "LEGAL", "EJECUTIVO"],
        customer_profiles=["EJECUTIVO", "VIP", "PROFESIONAL"],
        executive_level="high",
        premium_level="premium",
        commercial_value="high_value",
        gift_occasions=["RECONOCIMIENTO", "PREMIOS", "EVENTOS_CORPORATIVOS", "CIERRE_ANUAL"],
        campaigns=["RECONOCIMIENTO", "PREMIOS", "EVENTO_CORPORATIVO", "CIERRE"],
        use_cases=["EJECUTIVO", "FORMAL", "PRESENTACION"],
        corporate_affinity=0.9,
        perceived_value="alta_calidad",
        commercial_tags=["premium", "ejecutivo", "exclusivo", "formal", "lujo"],
        boost_tags=["ejecutivo", "vip", "premium", "exclusivo", "reconocimiento", "corporativo"],
    ),
    "PULSERA": _CommercialProfile(
        industries=["EVENTOS", "MODA", "CORPORATIVO", "SALUD", "BIENESTAR"],
        customer_profiles=["GENERAL", "JOVEN", "DEPORTISTA"],
        executive_level="low",
        premium_level="standard",
        commercial_value="economic",
        gift_occasions=["EVENTOS", "FERIAS", "PROMOCIONES", "CAMPAÑAS_SALUD"],
        campaigns=["EVENTO", "FERIA", "PROMOCION"],
        use_cases=["PULSERA", "IDENTIFICACION", "MODA", "CAUSA"],
        corporate_affinity=0.3,
        perceived_value="casual",
        commercial_tags=["casual", "promocional", "accesorio"],
        boost_tags=["evento", "feria", "promocional", "moda"],
    ),
    "ORGANIZADOR": _CommercialProfile(
        industries=["OFICINA", "CORPORATIVO", "TECNOLOGIA", "EDUCACION", "HOGAR"],
        customer_profiles=["EJECUTIVO", "ADMINISTRATIVO", "PROFESIONAL"],
        executive_level="medium",
        premium_level="standard",
        commercial_value="standard",
        gift_occasions=["OFICINA", "BIENVENIDA", "CAPACITACION", "EVENTOS"],
        campaigns=["OFICINA", "CAPACITACION", "EVENTO"],
        use_cases=["ORGANIZACION", "OFICINA", "ESCRITORIO", "ALMACENAMIENTO"],
        corporate_affinity=0.6,
        perceived_value="corporativo",
        commercial_tags=["corporativo", "oficina", "practico", "organizado"],
        boost_tags=["oficina", "corporativo", "organizado", "escritorio"],
    ),
    "BOLSO_TERMICO": _CommercialProfile(
        industries=["EVENTOS", "OUTDOOR", "SALUD", "LOGISTICA", "CONSTRUCCION"],
        customer_profiles=["TRABAJADOR", "EVENTO", "LOGISTICA", "DEPORTISTA"],
        executive_level="low",
        premium_level="standard",
        commercial_value="standard",
        gift_occasions=["EVENTOS_AIRE_LIBRE", "FERIAS", "CAPACITACION", "PICNIC"],
        campaigns=["EVENTO", "FERIA", "OBRA"],
        use_cases=["TRANSPORTE_ALIMENTOS", "EVENTOS", "REFRIGERACION"],
        corporate_affinity=0.4,
        perceived_value="practico",
        commercial_tags=["practico", "util", "eventos"],
        boost_tags=["evento", "feria", "construccion", "outdoor"],
    ),
    "REGALO": _CommercialProfile(
        industries=["CORPORATIVO", "EVENTOS", "FINANCIERO", "SEGUROS", "SALUD", "EDUCACION"],
        customer_profiles=["EJECUTIVO", "ADMINISTRATIVO", "COMERCIAL", "VIP"],
        executive_level="medium",
        premium_level="standard",
        commercial_value="standard",
        gift_occasions=["EVENTOS_CORPORATIVOS", "FERIAS", "LANZAMIENTOS", "CIERRE_ANUAL"],
        campaigns=["EVENTO_CORPORATIVO", "FERIA", "LANZAMIENTO", "CIERRE"],
        use_cases=["REGALO_CORPORATIVO", "PROMOCION", "EVENTOS"],
        corporate_affinity=0.7,
        perceived_value="corporativo",
        commercial_tags=["corporativo", "promocional", "regalo"],
        boost_tags=["corporativo", "evento", "feria", "lanzamiento", "regalo"],
    ),
    "ROPA": _CommercialProfile(
        industries=["CORPORATIVO", "EVENTOS", "SALUD", "EDUCACION", "TECNOLOGIA", "CONSTRUCCION"],
        customer_profiles=["GENERAL", "TRABAJADOR", "EJECUTIVO", "EVENTO"],
        executive_level="medium",
        premium_level="standard",
        commercial_value="standard",
        gift_occasions=["UNIFORMES", "EVENTOS", "FERIAS", "ACTIVACIONES"],
        campaigns=["UNIFORMES", "EVENTO", "FERIA", "ACTIVACION"],
        use_cases=["VESTIMENTA", "UNIFORME", "EVENTOS", "PROMOCION"],
        corporate_affinity=0.6,
        perceived_value="corporativo",
        commercial_tags=["corporativo", "uniforme", "textil"],
        boost_tags=["corporativo", "evento", "uniforme", "activacion"],
    ),
    "MALETA": _CommercialProfile(
        industries=["VIAJES", "CORPORATIVO", "CONSULTORIA", "TECNOLOGIA", "COMERCIAL"],
        customer_profiles=["EJECUTIVO", "VIAJERO", "COMERCIAL"],
        executive_level="high",
        premium_level="premium",
        commercial_value="valuable",
        gift_occasions=["VIAJES", "EVENTOS", "CONFERENCIAS", "BIENVENIDA", "RECONOCIMIENTO"],
        campaigns=["VIAJES", "EVENTO", "RECONOCIMIENTO", "BIENVENIDA"],
        use_cases=["VIAJES", "TRANSPORTE", "REUNIONES_EXTERNAS", "CONFERENCIAS"],
        corporate_affinity=0.8,
        perceived_value="ejecutivo",
        commercial_tags=["ejecutivo", "viajero", "profesional", "corporativo"],
        boost_tags=["ejecutivo", "viaje", "corporativo", "profesional", "reconocimiento"],
    ),
    "PORTAFOLIO": _CommercialProfile(
        industries=["CORPORATIVO", "CONSULTORIA", "LEGAL", "FINANCIERO", "VENTAS"],
        customer_profiles=["EJECUTIVO", "COMERCIAL", "PROFESIONAL"],
        executive_level="high",
        premium_level="premium",
        commercial_value="valuable",
        gift_occasions=["REUNIONES", "CONFERENCIAS", "CAPACITACION", "BIENVENIDA"],
        campaigns=["REUNIONES", "CAPACITACION", "BIENVENIDA"],
        use_cases=["DOCUMENTOS", "REUNIONES", "PRESENTACIONES", "OFICINA"],
        corporate_affinity=0.8,
        perceived_value="ejecutivo",
        commercial_tags=["ejecutivo", "profesional", "corporativo"],
        boost_tags=["ejecutivo", "corporativo", "profesional", "reunion"],
    ),
    "CABLE": _CommercialProfile(
        industries=["TECNOLOGIA", "TELECOMUNICACIONES", "ELECTRONICA", "CORPORATIVO"],
        customer_profiles=["TECNOLOGICO", "ADMINISTRATIVO", "GENERAL"],
        executive_level="low",
        premium_level="basic",
        commercial_value="economic",
        gift_occasions=["EVENTOS", "OFICINA", "TECNOLOGIA"],
        campaigns=["EVENTO", "OFICINA", "TECNOLOGIA"],
        use_cases=["CONEXION", "CARGA", "OFICINA", "HOGAR"],
        corporate_affinity=0.4,
        perceived_value="estandar",
        commercial_tags=["tecnologico", "util", "basico"],
        boost_tags=["tecnologia", "oficina", "evento"],
    ),
    "HUB": _CommercialProfile(
        industries=["TECNOLOGIA", "TELECOMUNICACIONES", "STARTUPS", "EDUCACION"],
        customer_profiles=["TECNOLOGICO", "EJECUTIVO", "PROFESIONAL"],
        executive_level="medium",
        premium_level="standard",
        commercial_value="standard",
        gift_occasions=["EVENTOS", "OFICINA", "TECNOLOGIA", "LANZAMIENTOS"],
        campaigns=["EVENTO_TECNOLOGIA", "OFICINA", "LANZAMIENTO"],
        use_cases=["CONEXION", "OFICINA", "TECNOLOGIA", "MULTITAREA"],
        corporate_affinity=0.5,
        perceived_value="corporativo",
        commercial_tags=["tecnologico", "corporativo", "oficina"],
        boost_tags=["tecnologia", "oficina", "startup"],
    ),
    "LONCHERA": _CommercialProfile(
        industries=["EDUCACION", "CONSTRUCCION", "SALUD", "EVENTOS"],
        customer_profiles=["ESTUDIANTE", "TRABAJADOR", "GENERAL"],
        executive_level="low",
        premium_level="basic",
        commercial_value="economic",
        gift_occasions=["UNIVERSIDAD", "OBRAS", "CAPACITACION"],
        campaigns=["UNIVERSIDAD", "OBRA", "CAPACITACION"],
        use_cases=["ALIMENTOS", "TRANSPORTE", "ESCUELA"],
        corporate_affinity=0.3,
        perceived_value="practico",
        commercial_tags=["practico", "util", "escolar"],
        boost_tags=["educacion", "obra", "practico"],
    ),
    "TECLADO": _CommercialProfile(
        industries=["TECNOLOGIA", "STARTUPS", "EDUCACION", "CORPORATIVO"],
        customer_profiles=["TECNOLOGICO", "ADMINISTRATIVO", "PROFESIONAL"],
        executive_level="medium",
        premium_level="standard",
        commercial_value="standard",
        gift_occasions=["OFICINA", "TELETRABAJO", "EVENTOS"],
        campaigns=["OFICINA", "TELETRABAJO", "EVENTO_TECNOLOGIA"],
        use_cases=["ESCRITURA", "OFICINA", "COMPUTACION"],
        corporate_affinity=0.5,
        perceived_value="corporativo",
        commercial_tags=["tecnologico", "corporativo"],
        boost_tags=["tecnologia", "oficina", "teletrabajo"],
    ),
    "MONEDERO": _CommercialProfile(
        industries=["CORPORATIVO", "FINANCIERO", "EVENTOS", "TECNOLOGIA"],
        customer_profiles=["GENERAL", "ADMINISTRATIVO", "COMERCIAL"],
        executive_level="low",
        premium_level="basic",
        commercial_value="economic",
        gift_occasions=["FERIAS", "EVENTOS", "PROMOCIONES"],
        campaigns=["FERIA", "EVENTO", "PROMOCION"],
        use_cases=["ORGANIZACION", "DINERO", "ACCESORIOS"],
        corporate_affinity=0.3,
        perceived_value="promocional",
        commercial_tags=["promocional", "practico"],
        boost_tags=["feria", "evento", "promocional"],
    ),
    "TARJETERO": _CommercialProfile(
        industries=["CORPORATIVO", "FINANCIERO", "CONSULTORIA", "LEGAL"],
        customer_profiles=["EJECUTIVO", "PROFESIONAL", "COMERCIAL"],
        executive_level="medium",
        premium_level="standard",
        commercial_value="standard",
        gift_occasions=["REUNIONES", "EVENTOS_CORPORATIVOS", "CONFERENCIAS", "BIENVENIDA"],
        campaigns=["REUNIONES", "EVENTO_CORPORATIVO", "BIENVENIDA"],
        use_cases=["TARJETAS", "DOCUMENTOS", "OFICINA"],
        corporate_affinity=0.6,
        perceived_value="corporativo",
        commercial_tags=["corporativo", "profesional", "ejecutivo"],
        boost_tags=["ejecutivo", "corporativo", "profesional", "reunion"],
    ),
}

CATEGORY_COMMERCIAL_TAGS: dict[str, list[str]] = {
    "Tecnologia": ["tecnologico", "moderno", "digital", "innovacion"],
    "Oficina": ["corporativo", "oficina", "papeleria", "profesional"],
    "Hogar": ["hogar", "practico", "util"],
    "Deportes": ["deportivo", "activo", "fitness", "energia"],
    "Textil": ["textil", "vestuario", "uniforme", "tela"],
    "Bolsos": ["ejecutivo", "viajero", "practico", "profesional"],
    "Termos": ["hidratacion", "termico", "aislante", "calidad"],
    "Eco": ["ecologico", "sostenible", "natural", "verde"],
    "Viaje": ["viajero", "portatil", "practico", "movilidad"],
    "Escritura": ["papeleria", "profesional", "oficina", "corporativo"],
    "Accesorios": ["accesorio", "complemento", "estilo"],
    "Libretas": ["papeleria", "profesional", "oficina", "creativo"],
    "Escolar": ["escolar", "estudiante", "educacion", "joven"],
    "Salud": ["salud", "bienestar", "cuidadopersonal"],
    "Belleza": ["belleza", "cuidadopersonal", "estetica"],
    "Moda": ["moda", "estilo", "tendencia"],
    "Musica": ["musica", "entretenimiento", "audio"],
    "Juguetes": ["juguete", "didactico", "entretenimiento"],
    "Herramientas": ["herramienta", "practico", "multiusos"],
}

MATERIAL_COMMERCIAL_TAGS: dict[str, dict] = {
    "RPET": {
        "perceived_value": "ecologico",
        "premium_level": "standard",
        "commercial_tags": ["ecologico", "sostenible", "reciclado"],
        "industries": ["EDUCACION", "TECNOLOGIA", "CONSULTORIA", "ECO"],
    },
    "BAMBU": {
        "perceived_value": "ecologico",
        "premium_level": "premium",
        "commercial_tags": ["ecologico", "natural", "organico", "premium"],
        "industries": ["EDUCACION", "CONSULTORIA", "SALUD", "BIENESTAR"],
    },
    "CORCHO": {
        "perceived_value": "ecologico",
        "premium_level": "standard",
        "commercial_tags": ["ecologico", "natural", "artesanal"],
        "industries": ["EDUCACION", "CONSULTORIA", "TECNOLOGIA", "ECO"],
    },
    "ALGODON": {
        "perceived_value": "natural",
        "premium_level": "standard",
        "commercial_tags": ["natural", "organico", "suave"],
        "industries": ["SALUD", "EDUCACION", "TEXTIL"],
    },
    "MADERA": {
        "perceived_value": "natural",
        "premium_level": "premium",
        "commercial_tags": ["natural", "rustico", "artesanal", "premium"],
        "industries": ["ARQUITECTURA", "CONSTRUCCION", "HOGAR"],
    },
    "METAL": {
        "perceived_value": "resistente",
        "premium_level": "premium",
        "commercial_tags": ["resistente", "duradero", "premium", "profesional"],
        "industries": ["CONSTRUCCION", "INGENIERIA", "INDUSTRIAL"],
    },
    "VIDRIO": {
        "perceived_value": "elegante",
        "premium_level": "premium",
        "commercial_tags": ["elegante", "fino", "premium", "sofisticado"],
        "industries": ["HOGAR", "EVENTOS", "HOTELERIA", "CORPORATIVO"],
    },
    "CERAMICA": {
        "perceived_value": "elegante",
        "premium_level": "premium",
        "commercial_tags": ["elegante", "artesanal", "premium", "decorativo"],
        "industries": ["HOGAR", "EVENTOS", "HOTELERIA"],
    },
    "SILICONA": {
        "perceived_value": "practico",
        "premium_level": "basic",
        "commercial_tags": ["practico", "flexible", "resistente"],
        "industries": ["SALUD", "COCINA", "HOGAR"],
    },
    "PLASTICO": {
        "perceived_value": "economico",
        "premium_level": "basic",
        "commercial_tags": ["economico", "ligero", "promocional"],
        "industries": ["GENERAL", "EVENTOS", "PROMOCIONAL"],
    },
    "CUERO": {
        "perceived_value": "premium",
        "premium_level": "luxury",
        "commercial_tags": ["premium", "lujo", "elegante", "clasico", "formal"],
        "industries": ["CORPORATIVO", "FINANCIERO", "LEGAL", "EJECUTIVO"],
    },
    "NEOPRENO": {
        "perceived_value": "practico",
        "premium_level": "standard",
        "commercial_tags": ["practico", "aislante", "deportivo"],
        "industries": ["DEPORTES", "OUTDOOR", "EVENTOS"],
    },
    "ACERO": {
        "perceived_value": "resistente",
        "premium_level": "premium",
        "commercial_tags": ["resistente", "duradero", "premium", "profesional", "inoxidable"],
        "industries": ["CONSTRUCCION", "INGENIERIA", "INDUSTRIAL"],
    },
    "INOXIDABLE": {
        "perceived_value": "resistente",
        "premium_level": "premium",
        "commercial_tags": ["resistente", "duradero", "premium", "profesional"],
        "industries": ["CONSTRUCCION", "INGENIERIA", "INDUSTRIAL"],
    },
    "ALUMINIO": {
        "perceived_value": "ligero",
        "premium_level": "standard",
        "commercial_tags": ["ligero", "resistente", "moderno"],
        "industries": ["CONSTRUCCION", "INDUSTRIAL", "TECNOLOGIA"],
    },
    "POLIESTER": {
        "perceived_value": "practico",
        "premium_level": "basic",
        "commercial_tags": ["practico", "resistente", "textil"],
        "industries": ["TEXTIL", "DEPORTES", "CORPORATIVO"],
    },
    "POLIPROPILENO": {
        "perceived_value": "practico",
        "premium_level": "basic",
        "commercial_tags": ["practico", "ligero", "resistente"],
        "industries": ["INDUSTRIAL", "GENERAL"],
    },
    "CAUCHO": {
        "perceived_value": "practico",
        "premium_level": "basic",
        "commercial_tags": ["practico", "flexible", "antideslizante"],
        "industries": ["INDUSTRIAL", "DEPORTES", "SALUD"],
    },
    "TELA": {
        "perceived_value": "suave",
        "premium_level": "standard",
        "commercial_tags": ["suave", "textil", "practico"],
        "industries": ["TEXTIL", "HOGAR", "CORPORATIVO"],
    },
    "YUTE": {
        "perceived_value": "ecologico",
        "premium_level": "standard",
        "commercial_tags": ["ecologico", "natural", "rustico"],
        "industries": ["EDUCACION", "ECO", "HOGAR"],
    },
    "LONA": {
        "perceived_value": "practico",
        "premium_level": "basic",
        "commercial_tags": ["practico", "resistente", "textil"],
        "industries": ["CONSTRUCCION", "EVENTOS", "PUBLICIDAD"],
    },
    "SINTETICO": {
        "perceived_value": "practico",
        "premium_level": "basic",
        "commercial_tags": ["practico", "resistente", "textil"],
        "industries": ["TEXTIL", "DEPORTES"],
    },
}

PERCEIVED_VALUE_LEVEL_MAP: dict[str, str] = {
    "alto": "alta_calidad",
    "medio": "corporativo",
    "bajo": "estandar",
}
